##############################################
#            Server Configuration            #
##############################################
server:
  port: 3000
  error:
    include-message: always


##############################################
#           Database Configuration           #
##############################################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice
    username: root
    password: q1w2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: create
